### ISSUE TITLE
Fix error experienced in web_interface when receiving a mission

### ISSUE THREAD

**Issue by mhoejgaard** [RMUASD-Team2-2017/UASD#53]
Traceback (most recent call last):
  File "/home/mathias/UASD/catkin_ws/src/GCS/src/web_interface_node.py", line 54, in <module>
    main()
  File "/home/mathias/UASD/catkin_ws/src/GCS/src/web_interface_node.py", line 40, in main
    (update_count,lat,lng,alt) = interface.getDeployRequest()
  File "/home/mathias/UASD/git/UASD/GCS/src/web_interface.py", line 47, in getDeployRequest
    if(not self.active and int(jsonformat[0]["completed"]) == 0):   # If a mission is not active and the newest request is uncompleted
KeyError: 0

**Comment by mhoejgaard** [comment]
The above error means that the values returned by the api are an indexed list whereas it was a standard json list before.

The change from standard to indexes list was an error on the database side. It has now been returned to a regular json list.

No further work needs to be done on the ros web_interface_node.
